"""
This type stub file was generated by pyright.
"""

from ansible.module_utils.compat import _selectors2 as selectors

__metaclass__ = type
_BUNDLED_METADATA = ...
if _system_selectors:
    selectors = ...
else: ...
