"""
This type stub file was generated by pyright.
"""

__all__ = ["add_bookmarks", "delete_bookmarks", "clean_bookmarks"]
from collections.abc import Sequence
from typing import Optional

def get_default_config_path() -> str:
    """Return the default path to the configuration file."""
    ...

def add_bookmarks(paths: Sequence[str], config_path: Optional[str] = None) -> None:
    """Add a list of paths as bookmarks to the config file."""
    ...

def delete_bookmarks(paths: Sequence[str], config_path: Optional[str] = None) -> None:
    """Remove a list of paths from the bookmark config file."""
    ...

def clean_bookmarks(config_path: Optional[str] = None) -> None:
    """Delete any bookmarks that don't exist."""
    ...
