"""
This type stub file was generated by pyright.
"""

"""Collections ABC import shim.

This module is intended only for internal use.
It will go away once the bundled copy of six includes equivalent functionality.
Third parties should not use this.
"""
__metaclass__ = type
