"""
This type stub file was generated by pyright.
"""

__metaclass__ = type

def get_best_parsable_locale(module, preferences=..., raise_on_locale=...):
    """
    Attempts to return the best possible locale for parsing output in English
    useful for scraping output with i18n tools. When this raises an exception
    and the caller wants to continue, it should use the 'C' locale.

    :param module: an AnsibleModule instance
    :param preferences: A list of preferred locales, in order of preference
    :param raise_on_locale: boolean that determines if we raise exception or not
                            due to locale CLI issues
    :returns: The first matched preferred locale or 'C' which is the default
    """
    ...
