"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, division, print_function

import sys
import types

from ansible.module_utils.distro import _distro as distro

__metaclass__ = type
_BUNDLED_METADATA = ...
if _system_distro:
    distro = ...
else: ...
